HTTP = "http://"
JOB_HOST_LOCAL = HTTP + "localhost"
JOB_PORT_LOCAL = 8081
JOB_HOST_REMOTE = HTTP + "REMOTE URL WITHOUT HTTP -> myurl.com" #MUST BE MODIFIED
JOB_PORT_REMOTE = "REMOTE PORT" #MUST BE MODIFIED
DEBUG = False

##STATS DATABASE
SQL_HOST = "localhost"
SQL_PORT = "61111"
SQL_USER = "myuser"
SQL_PASSWORD = "password"
SQL_DATABASE = "jsdoop"


##DATASETS
MNIST = "mnist"

##TOPOLOGIES
MNIST_CONV_28_28_1 = "mnist_conv_28_28_1"
